### ISSUE TITLE
“用户管理/编辑/权限”修改并取消后，”用户列表“中的权限数据错误

### ISSUE THREAD

**Issue by Taskeren** [MCSManager/UI#10]
“用户管理/编辑/权限”修改并取消后，”用户列表“中的权限数据错误。
例如我将 A 的权限从 最高 改成 普通，然后点取消关闭窗口，用户列表显示的权限为 普通，然而实际是 最高，并且刷新后变成正确的 最高。

顺便，直接刷新会导致用户列表没有任何数据，显示暂无数据。

**Comment by Suwings** [comment]
已修复，将在今晚的版本中更新。
