### ISSUE TITLE
颜色错误

### ISSUE THREAD

**Issue by RimuruChan** [MCSManager/UI#15]
https://github.com/MCSManager/UI/blob/1d6e438648f973f7e9e99bebbecd00931501a86c/src/app/service/term.js#L87

**Comment by Suwings** [comment]
就这一行代码的话，你提个 PR 呗，我很欢迎的。

**Comment by RimuruChan** [comment]
我再看看😂

**Comment by RimuruChan** [comment]
#16

**Comment by RimuruChan** [comment]
> 就这一行代码的话，你提个 PR 呗，我很欢迎的。

改了亿行

**Comment by huangsijun17** [comment]
> > 就这一行代码的话，你提个 PR 呗，我很欢迎的。
> 
> 改了亿行

雀食。

**Comment by RimuruChan** [comment]
#17
