### ISSUE TITLE
[BUG] 无法删除没有名称的Docker镜像

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/UI#19]
**操作系统版本**
Ubuntu 20.04

**面板版本**
[f027040](https://github.com/MCSManager/UI/commit/f0270400ea91bc4808bdaf0bba7338081e9a7d12)

**出现概率**
100%

**BUG 详情描述**
新建 Docker 镜像失败后，若未能对其命名，则无法被删除。

**复现步骤**
新建一个无名称的 Docker 镜像，尝试删除该镜像。

**Comment by Suwings** [comment]
提供的 API 没有办法通过 ID 来删除镜像，这个依赖库的 API 目前好像只能通过名称来删除镜像，所以暂时没办法修复，就这样把。

**Comment by Suwings** [comment]
https://www.npmjs.com/package/docker-modem
