### ISSUE TITLE
[Feature]可选隐藏Docker镜像

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/UI#20]
**面板版本**
[f027040](https://github.com/MCSManager/UI/commit/f0270400ea91bc4808bdaf0bba7338081e9a7d12)

**想法/建议**
可选得，隐藏部分Docker镜像，以便于隐藏下载的原版openjdk等镜像。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
每个使用Docker，切构建多个版本的使用者。
![image](https://user-images.githubusercontent.com/31504595/152954108-2d565eb3-a506-4f95-aa7a-9d61d775a449.png)

**Comment by RimuruChan** [comment]
感觉没必要。。。
而且其实没必要构建一个新的docker image
你pull下来的image可以直接用的。

**Comment by huangsijun17** [comment]
> 感觉没必要。。。 而且其实没必要构建一个新的docker image 你pull下来的image可以直接用的。

时区没设置，运行目录没建立，没设置。

**Comment by RimuruChan** [comment]
这么说也是。。
不过我还是觉得没必要隐藏
你自己给生成的镜像命名就能区分了
话说运行目录不是服务端目录吗？

**Comment by huangsijun17** [comment]
> 这么说也是。。 不过我还是觉得没必要隐藏 你自己给生成的镜像命名就能区分了 话说运行目录不是服务端目录吗？

```
RUN mkdir -p /workspace
WORKDIR /workspace
```

这是MCSM自带的DockerFiles里的参数，修改容器内的工作目录。

**Comment by RimuruChan** [comment]
> > 这么说也是。。 不过我还是觉得没必要隐藏 你自己给生成的镜像命名就能区分了 话说运行目录不是服务端目录吗？
> 
> ```
> RUN mkdir -p /workspace
> WORKDIR /workspace
> ```
> 
> 这是MCSM自带的DockerFiles里的参数，修改容器内的工作目录。
> 
> 另外，MCSM的Docker镜像不以镜像名排列。自己命名完，照样乱糟糟的。

我并没有设置工作目录，照样可以用，，
隐藏算了，排序可以弄一下

**Comment by Suwings** [comment]
不做隐藏。

**Comment by huangsijun17** [comment]
> 不做隐藏。

排序可行不？
