### ISSUE TITLE
[BUG]输入框未对插入键（Insert key)按下做出正确相应。

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/UI#35]
**操作系统版本**
Windows 10
**面板版本**
9.3.2
**出现概率**
100%
**BUG 详情描述**
任意输入框，按下插入键后，未切换文本输入模式。无法从插入模式修改为覆盖模式。
**复现步骤**
按下插入键。

**Comment by Suwings** [comment]
你是说的 MCSManager 终端底部的 HTML 网页输入框吗？这个输入框应该本来就不支持 Insert 模式吧？

**Comment by huangsijun17** [comment]
> 你是说的 MCSManager 终端底部的 HTML 网页输入框吗？这个输入框应该本来就不支持 Insert 模式吧？

各处的似乎都不支持。而且，我目测是上游的问题。
