### ISSUE TITLE
[BUG]控制台字体异常

### ISSUE THREAD

**Issue by pthmz** [MCSManager/UI#36]
**操作系统版本**
操作系统名称	Microsoft Windows 10 专业版
版本	10.0.19044 内部版本 19044
FireFox 98.0 (64 位)
**面板版本**
![图片](https://user-images.githubusercontent.com/97567575/157810489-e46b693f-2b09-40f8-b783-a5955806f867.png)

**出现概率**
50%

**BUG 详情描述**
控制台所有字就出现类似全角字体的样式，间距很大，非常难以阅读，这时，我只好在控制台页面直接刷新网页，才能使字体正常。
![图片](https://user-images.githubusercontent.com/97567575/157810519-d47c082f-6791-4cc0-b53c-88c0dc1e80c6.png)
![图片](https://user-images.githubusercontent.com/97567575/157811422-c3bdd258-fb95-48fd-a3b9-166da48aa54b.png)
![图片](https://user-images.githubusercontent.com/97567575/157810559-0ba3d115-02db-46cd-98e9-6a641be6be8e.png)
![图片](https://user-images.githubusercontent.com/97567575/157810569-53a3e7d9-f910-4401-ba0f-4692004dd3cf.png)

**复现步骤**
打开网站，点开应用实例，随便看准一个实例点击它右边的管理
![图片](https://user-images.githubusercontent.com/97567575/157810573-37571728-5d9d-4acb-b861-574eb05e7de5.png)

**Comment by huangsijun17** [comment]
其他浏览器开启是否支持？

**Comment by pthmz** [comment]
> 

Chrome 正常。版本 99.0.4844.51（正式版本） （64 位）

**Comment by huangsijun17** [comment]
FireFox 98.0 (64 位)测试异常。

我发现控制台有显示：
```
通过 link preload 预加载的资源“http://mc.mengmeet.cn:23333/static/FiraCode-Regular.ttf”并未在加载后几秒内使用。请确保 preload 标签的所有属性均设置无误。
```

字体加载问题？

**Comment by Suwings** [comment]
应该是字体文件没有能正确加载，MCSM 控制台需要一个字体文件支持，请按 F12 点 network 选项卡查看 FiraCode-Regular.ttf 是否正确请求。

**Comment by pthmz** [comment]
我是无影云桌面上的面板和服，用其他云服务器nps穿透的网络，和这些有影响吗？

**Comment by pthmz** [comment]
![图片](https://user-images.githubusercontent.com/97567575/157993679-3c2d20b2-a0a8-4c61-918b-21c61603b553.png)
![图片](https://user-images.githubusercontent.com/97567575/157993707-14952c59-ef1c-4a0f-bc12-b2940c327615.png)

**Comment by Suwings** [comment]
已修复。
