### ISSUE TITLE
[Feature]设置面板端时间显示格式

### ISSUE THREAD

**Issue by Glucy-2** [MCSManager/UI#37]
**面板版本**
9.3.2

**想法/建议**
设置面板端时间显示格式（Linux）
![image](https://user-images.githubusercontent.com/53287753/159105812-0ecb841d-45d8-404e-935d-cd483c10f847.png)
如图，面板上显示的面板端时间格式是`MM/dd/yyyy, HH;mm:ss`如何更改？
设置环境变量TIME_STYLE不起作用
locale：
````sh
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
````
相关代码：
https://github.com/MCSManager/UI/blob/7f7251b680fdb1c459543ce655b9513687c3b667/src/app/views/Overview.vue#L329
**您认为这个想法/建议在每100人中会有多少人遇到/使用**
（我觉得不多

**Comment by Suwings** [comment]
无法更改，必须改代码。
