### ISSUE TITLE
[BUG] 无法正常下载日志文件

### ISSUE THREAD

**Issue by lss233** [MCSManager/UI#44]
**操作系统版本**
面板系统：
![image](https://user-images.githubusercontent.com/8984680/161027620-838561bb-560d-43a3-b88d-d46fd8faa1d1.png)
用户系统：
操作系统名称 Microsoft Windows 10 专业版
版本 10.0.19044 内部版本 19044
Chrome/99.0.4844.84
**面板版本**
9.3

**出现概率**
80%

**BUG 详情描述**
想把日志文件下载到本地，但是从文件管理里点击下载会变成在浏览器内直接打开
右键 **另存为** 也无法下载。
![image](https://user-images.githubusercontent.com/8984680/161027799-0ed08c63-e308-401d-a6d6-b13d7b219d3b.png)
![image](https://user-images.githubusercontent.com/8984680/161028012-7fa1ef40-b57f-4a02-a25d-1294d00c4c4f.png)
![image](https://user-images.githubusercontent.com/8984680/161028282-36f48edb-d3c1-436c-aedd-ce9f804afae7.png)

**复现步骤**
文件管理 -> logs -> latests.log 下载

**Comment by Suwings** [comment]
感谢反馈，这个确实是bug，后期将会慢慢修复。

**Comment by lss233** [comment]
本来以为这是个前端的BUG。但是似乎可以在 Daemon [这里](https://github.com/MCSManager/Daemon/blob/00ee1f1e599da9574e1d981f1a23851f91443c0c/src/routers/http_router.ts#L55)加一个 `Content-Disposition` 的头来解决这个问题？

**Comment by Suwings** [comment]
> 本来以为这是个前端的BUG。但是似乎可以在 Daemon [这里](https://github.com/MCSManager/Daemon/blob/00ee1f1e599da9574e1d981f1a23851f91443c0c/src/routers/http_router.ts#L55)加一个 `Content-Disposition` 的头来解决这个问题？

可能就是这么简单，这个问题你可以提交一个 PR 来进行修复，可以本地进行测试后提交。

**Comment by Suwings** [comment]
已修：https://github.com/MCSManager/MCSManager/releases/tag/v9.4.2
