### ISSUE TITLE
[BUG]Docker镜像在镜像列表内重复显示

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/UI#46]
**操作系统版本**
Windows11
Edge100.0.1185.39 (x64)

**面板版本**
9.4.2

**出现概率**
100%

**BUG 详情描述**
Docker 镜像列表重复显示。

**复现步骤**
“实例详细信息设置”中，选择完Docker镜像并单击“保存配置”，镜像列表中的镜像被再次拉取，而重复显示。

![image](https://user-images.githubusercontent.com/31504595/163558209-fb0a5713-81e4-47e8-939e-36679622bb7c.png)

**Comment by Suwings** [comment]
镜像列表中的镜像被再次拉取，而重复显示。

什么意思？我没懂。

**Comment by huangsijun17** [comment]
> 镜像列表中的镜像被再次拉取，而重复显示。
> 
> 什么意思？我没懂。

例如镜像列表为：A、B两个镜像，点一次保存后就显示为A、B、A、B这样四个，再点一次变成六个。
我这镜像太多了，不好截图。

**Comment by Suwings** [comment]
最新的开发代码已经修复，会随着下个版本一并发出
