### ISSUE TITLE
这个仓库名不太合适吧

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/UI#5]
仓库名叫ui的话，克隆下来的文件夹名也会叫UI，容易和别的文件夹同名。Daemon也是。建议改成MCSM_UI或者McsmUI等。

**Comment by KagurazakaNyaa** [comment]
如果是通过submodule方式组织项目应该就比较合适了

**Comment by Suwings** [comment]
不会不合适，因为这些是 Typescript 代码不可直接运行于 NodeJS，所以 Clone 下来的话一般是用于开发的，开发模式下 UI 内嵌的 Webpack 反向代理会将所有请求代理到 Web 端，所以三个项目分开不管名字叫什么都不会有任何影响。

也就是说，开发人员才需要这三个仓库，以后的线上生产代码会额外提供一个仓库存储，里面理论上应该是编译好的 JavaScript 压缩代码，供客户直接使用，参考源码就还是得来着三个仓库：UI，Web，Daemon。

你考虑的应该还是 MCSM8 的那种线上源码即生产环境源码的情况，MCSM 9 的源代码不可直接运行，除非采用 ts-node 依赖模块来直接运行 Typescript。

**Comment by Suwings** [comment]
另外你说的 UI 容易重名问题，你建一个文件夹叫 MCSManager，在里面进行 Clone 就好了嘛。

**Comment by huangsijun17** [comment]
> 另外你说的 UI 容易重名问题，你建一个文件夹叫 MCSManager，在里面进行 Clone 就好了嘛。

不是给用户的就行。我是怕拿来用的下下来后重名。

**Comment by Suwings** [comment]
这个仓库普通用户是无法用的，它需要把前端编译成js文件之后，再移动放入web项目的public目录中，这个项目在生产环境下就不会独立存在运行。
