### ISSUE TITLE
“实例文件编辑/编辑源文件视图” 没有直接返回控制台的按钮

### ISSUE THREAD

**Issue by Taskeren** [MCSManager/UI#7]
“实例文件编辑/编辑源文件视图” 没有直接返回控制台的按钮，需要切换回简单模式再返回

**Comment by Suwings** [comment]
已了解，此 Issue 先不关闭，待以后有时间新增此功能之后再关闭。

**Comment by Suwings** [comment]
十分抱歉，经过研究，此功能暂时不进行添加，参数传递略微麻烦，待主体功能完善后在进行细节优化，谢谢你的提议。
